version: '3.8'
services:

  config-service:
    image: seungilbang/spring-cloud-ecosystem:config
    container_name: config-service
    ports:
      - "8888:8888"
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:8888/actuator/health" ]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - spring-cloud-network

networks:
  spring-cloud-network:
    driver: bridge
