spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: ${SPRING_CLOUD_CONFIG_SERVER_URI:https://github.com/Seung-IL-Bang/spring-cloud-ecosystem-remote-config.git}
    bus:
      destination: ${SPRING_CLOUD_BUS_DESTINATION:bus-topic}
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:http://localhost:9092}

server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: health