spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Seung-IL-Bang/spring-cloud-ecosystem-remote-config.git

server:
  port: 8888